### ISSUE TITLE
A3 - README and Documentation 

### ISSUE THREAD

**Issue by KafkaNoNeko** [cosc-310-group32/Assignment3#1]
- [x] Update README for A3
       - A list of all the features programmed for Assignment 3
       - For each item, explain briefly how it was used to improve the conversation/overall system
       - For each explanation, include a snippet of conversation as an example

- [x] Level 0 Data Flow Diagram (DFD) for the system with description

- [x] Level 1 DFD for the system with description. 

- [x] Submission of GitHub repo. Graph showing different features 
developed on a separate branch and the commits made in the repository. 

- [x] Sample output (30 turns; show new features). Show two short dialogues for when the bot does not work properly

- [x] List of limitations

- [x] List of at least 5 features that you can extract from your code or design that can be shared with others as an API.

**Comment by aksingal-dev** [comment]
Refer to documentation branch for WIP updates
